name: Node.js CI Publish npm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set env from secrets
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        echo "Setting environment variables from GitHub Secrets"

    - name: Install dependencies
      run: |
        npm install
    
    - name: Configure npm to use the token
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

    - name: Build
      run: |
        npm run build

    - name: Publish package
      run: npm publish --access public